import { Plus, Search, Trash2, Waypoints } from "lucide-react";
import type { EplusRawFormSchema, EventSnapshot } from "../../shared/ipc.js";
import { ProgressBar } from "./ProgressBar.js";

export interface EventForm { sourceUrl: string; canonicalUrl: string; title: string; venue: string; scheduleText: string; applicationDeadline: string; pageFingerprint: string; rawFormSchemaJson: string; }
interface EventDiscoveryProps { readonly form: EventForm; readonly schema: EplusRawFormSchema; readonly events: readonly EventSnapshot[]; readonly parsing: boolean; readonly saving: boolean; readonly onFormChange: (form: EventForm) => void; readonly onDiscover: () => void; readonly onSave: () => void; readonly onDeleteEvent: (id: string) => void; }

export function EventDiscovery(props: EventDiscoveryProps) {
  const links = props.schema.applicationLinks.length;
  return <section className="workspace-panel" aria-labelledby="events-title"><div className="workspace-heading"><div><p className="section-kicker">演出与任务</p><h1 id="events-title">演出快照</h1><p>从 Eplus 页面提取结构化信息，确认后保存为可复用的任务快照。</p></div><span className={props.schema.requiresManualInspection ? "badge badge-yellow" : "badge badge-green"}>{props.schema.requiresManualInspection ? "需要人工检查" : "可创建任务"}</span></div><section className="panel-card"><div className="panel-head"><h2><Waypoints size={16} />页面解析</h2><span className="muted">先解析，再核对页面结构和场次</span></div>{props.parsing ? <ProgressBar label="正在解析页面" /> : null}<div className="form-grid"><label className="full">来源网址<input value={props.form.sourceUrl} placeholder="粘贴 Eplus 演出页面网址" onChange={(event) => props.onFormChange({ ...props.form, sourceUrl: event.target.value })} /></label><label className="full">演出标题<input value={props.form.title} placeholder="解析后自动填入，也可手动修正" onChange={(event) => props.onFormChange({ ...props.form, title: event.target.value })} /></label><label>会场<input value={props.form.venue} placeholder="演出会场" onChange={(event) => props.onFormChange({ ...props.form, venue: event.target.value })} /></label><label>申请截止时间<input value={props.form.applicationDeadline} placeholder="例如：2026-08-01 23:59" onChange={(event) => props.onFormChange({ ...props.form, applicationDeadline: event.target.value })} /></label><label className="full">场次说明<textarea rows={3} value={props.form.scheduleText} placeholder="补充场次、日期或注意事项" onChange={(event) => props.onFormChange({ ...props.form, scheduleText: event.target.value })} /></label><label className="full">页面结构 JSON<textarea rows={8} value={props.form.rawFormSchemaJson} onChange={(event) => props.onFormChange({ ...props.form, rawFormSchemaJson: event.target.value })} /></label></div><div className="schema-summary"><div className="summary-grid"><div><strong>{links}</strong><span>申请入口</span></div><div><strong>{props.schema.options.length}</strong><span>表单选项</span></div><div><strong>{props.schema.serialCode.required ? "需要" : "不需要"}</strong><span>抽选码</span></div><div><strong>{props.schema.sourceKind === "serial-code" ? "抽选码" : "标准"}</strong><span>页面类型</span></div></div>{props.schema.notes.map((note) => <p key={note} className="muted">{note}</p>)}</div><div className="actions"><button className="icon-button" disabled={props.parsing} onClick={props.onDiscover} title="从来源网址提取页面结构"><Search size={16} />{props.parsing ? "正在解析" : "解析页面"}</button><button className="primary" disabled={props.saving} onClick={props.onSave}><Plus size={16} />{props.saving ? "正在保存" : "保存快照"}</button></div></section>
  <section className="panel-card"><div className="panel-head"><h2><Waypoints size={16} />已保存快照</h2><span className="muted">{props.events.length} 个快照 · 过期或解析有误的快照可删除后重新解析</span></div><div className="table-wrap"><table><thead><tr><th>标题</th><th>会场</th><th>页面类型</th><th>解析时间</th><th aria-label="操作" /></tr></thead><tbody>{props.events.map((event) => <tr key={event.id}><td>{event.title}</td><td>{event.venue || "-"}</td><td>{event.rawFormSchema.sourceKind === "serial-code" ? "抽选码" : event.rawFormSchema.sourceKind === "standard-detail" ? "标准" : "未知"}</td><td>{new Date(event.fetchedAt).toLocaleString()}</td><td className="row-actions"><button className="icon-button danger" onClick={() => props.onDeleteEvent(event.id)} title="删除快照" aria-label={`删除快照 ${event.title}`}><Trash2 size={15} /></button></td></tr>)}</tbody></table></div>{props.events.length === 0 ? <p className="empty-state">尚未保存任何演出快照。先解析页面并保存。</p> : null}</section></section>;
}
