import { AlertTriangle, CheckCircle2, CirclePause, Play, ShieldAlert, XCircle } from "lucide-react";
import type { Account, AccountRun, CreateTaskInputV2, EventSnapshot, LotteryPreference } from "../../shared/ipc.js";
type ConfirmationPolicy = CreateTaskInputV2["confirmationPolicy"];
export interface TaskDraft { readonly accountIds: string[]; readonly confirmationPolicy: ConfirmationPolicy; readonly preference: LotteryPreference; readonly riskAcknowledged: boolean; }
interface TaskPolicyControlsProps { readonly automated: boolean; readonly policy: ConfirmationPolicy; readonly acknowledged: boolean; readonly onPolicyChange: (policy: ConfirmationPolicy) => void; readonly onAcknowledgedChange: (value: boolean) => void; }
export function TaskPolicyControls(props: TaskPolicyControlsProps) { if (!props.automated) return null; return <div className="disclosure-stack" aria-label="自动化风险说明"><div className="disclosure disclosure-warning"><ShieldAlert size={18} aria-hidden="true" /><div><strong>自动化风险确认</strong><span>Eplus 条款可能限制自动化申请。请在创建任务前检查每个账号。</span></div></div><label className="full">最终确认策略<select value={props.policy} onChange={(event) => props.onPolicyChange(event.target.value === "disabled" ? "disabled" : "required")}><option value="required">需要确认：最终提交前暂停</option><option value="disabled">自动提交：不暂停</option></select></label><p className="muted">{props.policy === "disabled" ? "自动提交：每个账号提交前不会额外暂停。" : "需要确认：每个账号会在最终提交前等待明确确认。"}</p><label className="check-row"><input type="checkbox" checked={props.acknowledged} onChange={(event) => props.onAcknowledgedChange(event.target.checked)} />我已了解以上条款和自动化风险。</label></div>; }
interface PerAccountReviewProps { readonly accounts: readonly Account[]; readonly event: EventSnapshot | undefined; readonly draft: TaskDraft; readonly onDraftChange: (draft: TaskDraft) => void; }
function accountName(account: Account): string { return account.label || account.eplusEmail; }
export function PerAccountReview(props: PerAccountReviewProps) { const accounts = props.accounts.filter((account) => props.draft.accountIds.includes(account.id)); const days = props.event?.rawFormSchema.serialCode.availableDays ?? []; const needsDays = Boolean(props.event?.rawFormSchema.serialCode.daySelectionRequired && days.length > 1); const codes = props.draft.preference.serialCodesByAccountId ?? {}; const selections = props.draft.preference.daySelectionByAccountId ?? {}; const changeCode = (id: string, code: string) => props.onDraftChange({ ...props.draft, preference: { ...props.draft.preference, serialCodesByAccountId: { ...codes, [id]: code } } }); const toggleDay = (id: string, day: "day1" | "day2") => { const current = selections[id] ?? []; props.onDraftChange({ ...props.draft, preference: { ...props.draft.preference, daySelectionByAccountId: { ...selections, [id]: current.includes(day) ? current.filter((item) => item !== day) : [...current, day] } } }); }; return <div className="account-review-list">{accounts.map((account) => <article key={account.id} className="account-review"><div><strong>{accountName(account)}</strong><span>{account.eplusEmail}</span></div>{needsDays ? <div className="review-days" aria-label={`${accountName(account)}的场次选择`}>{days.map((day) => <label key={day} className="check-row"><input type="checkbox" checked={(selections[account.id] ?? []).includes(day)} onChange={() => toggleDay(account.id, day)} />{day === "day1" ? "第一天" : "第二天"}</label>)}</div> : null}{props.event?.rawFormSchema.serialCode.required ? <label>抽选码<input value={codes[account.id] ?? props.draft.preference.serialCode ?? ""} onChange={(event) => changeCode(account.id, event.target.value)} /></label> : null}<span className={props.draft.confirmationPolicy === "disabled" ? "badge badge-yellow" : "badge badge-teal"}>{props.draft.confirmationPolicy === "disabled" ? "自动提交" : "需要最终确认"}</span></article>)}{accounts.length === 0 ? <p className="empty-state">至少选择一个已启用账号，才能预览其实际偏好。</p> : null}</div>; }
interface PreviewDigestProps { readonly event: EventSnapshot | undefined; readonly draft: TaskDraft; readonly accounts: readonly Account[]; }
export function PreviewDigest(props: PreviewDigestProps) { const selected = props.accounts.filter((account) => props.draft.accountIds.includes(account.id)); const days = props.draft.preference.daySelectionByAccountId ?? {}; return <div className="preview-digest" aria-live="polite"><div><span>演出</span><strong>{props.event?.title ?? "未选择演出快照"}</strong></div><div><span>账号</span><strong>{selected.length}</strong></div><div><span>策略</span><strong>{props.draft.confirmationPolicy === "disabled" ? "自动提交" : "需要最终确认"}</strong></div><div><span>场次选择</span><strong>{Object.values(days).filter((selection) => selection.length > 0).length || "不需要"}</strong></div></div>; }
interface ManualTakeoverPanelProps { readonly runs: readonly AccountRun[]; readonly accounts: readonly Account[]; readonly onAction: (run: AccountRun, action: "continue" | "cancel-account" | "cancel-task" | "reconcile-unknown") => void; }
export function ManualTakeoverPanel(props: ManualTakeoverPanelProps) { const runs = props.runs.filter((run) => run.status === "AwaitingManualAction" || run.status === "UnknownSubmissionState"); if (!runs.length) return null; return <section className="panel-card manual-takeover" aria-label="人工接管面板"><div className="panel-head"><h2><CirclePause size={16} />人工接管面板</h2><span className="badge badge-yellow">需要处理</span></div><div className="stack">{runs.map((run) => { const account = props.accounts.find((item) => item.id === run.accountId); const unknown = run.status === "UnknownSubmissionState"; return <div key={run.id} className="takeover-row"><div><strong>{account?.label || account?.eplusEmail || run.accountId}</strong><span>{unknown ? "提交状态未知" : "等待人工接管"}</span><p>{run.errorDetailRedacted || (unknown ? "提交状态不明确。再次操作前请先查证。" : "浏览器需要人工决策后才能继续。")}</p></div><div className="row-actions">{unknown ? <button type="button" className="icon-button" onClick={() => props.onAction(run, "reconcile-unknown")}><CheckCircle2 size={15} />查证提交状态</button> : <button type="button" className="icon-button" onClick={() => props.onAction(run, "continue")}><Play size={15} />继续</button>}<button type="button" className="icon-button danger" onClick={() => props.onAction(run, "cancel-account")}><XCircle size={15} />取消账号</button><button type="button" className="icon-button danger" onClick={() => props.onAction(run, "cancel-task")}><AlertTriangle size={15} />取消任务</button></div></div>; })}</div></section>; }
