import { CheckCircle2, CirclePause, Play, XCircle } from "lucide-react";
import type { Account, AccountRun, DashboardState } from "../../shared/ipc.js";
import { ManualTakeoverPanel } from "./TaskWorkflow.js";

const statusText: Record<string, string> = { Pending: "待处理", Queued: "已排队", LoggingIn: "正在登录", FillingForm: "正在填写", AwaitingConfirmation: "等待确认", AwaitingEmailCode: "等待验证码", AwaitingManualAction: "等待人工接管", UnknownSubmissionState: "提交状态未知", AwaitingSubmitConfirmation: "等待最终确认", Submitting: "正在提交", Running: "运行中", Paused: "已暂停", Submitted: "已提交", Completed: "已完成", Failed: "失败", Cancelled: "已取消" };
const statusTone: Record<string, string> = { Pending: "gray", Queued: "blue", LoggingIn: "blue", FillingForm: "blue", AwaitingConfirmation: "yellow", AwaitingEmailCode: "yellow", AwaitingManualAction: "yellow", UnknownSubmissionState: "yellow", AwaitingSubmitConfirmation: "yellow", Submitting: "teal", Running: "teal", Paused: "yellow", Submitted: "green", Completed: "green", Failed: "red", Cancelled: "gray" };
interface TaskMonitorProps { readonly state: DashboardState; readonly onEnqueue: (taskId: string) => void; readonly onPause: () => void; readonly onResume: () => void; readonly onCancelTask: (taskId: string) => void; readonly onCancelRun: (runId: string) => void; readonly onManualAction: (run: AccountRun, action: "continue" | "cancel-account" | "cancel-task" | "reconcile-unknown") => void; }
function StatusBadge({ status }: { readonly status: string }) { return <span className={`badge badge-${statusTone[status] ?? "gray"}`}>{statusText[status] ?? status}</span>; }
export function TaskMonitor(props: TaskMonitorProps) { return <section className="workspace-panel" aria-labelledby="monitor-title"><div className="workspace-heading"><div><p className="section-kicker">演出与任务</p><h1 id="monitor-title">任务监控</h1><p>保守处理队列、运行状态和人工决策。未知提交状态不会自动重试。</p></div><div className="cluster"><button className="icon-button" onClick={props.onPause}><CirclePause size={16} />暂停队列</button><button className="icon-button" onClick={props.onResume}><Play size={16} />恢复队列</button></div></div><ManualTakeoverPanel runs={props.state.runs} accounts={props.state.accounts} onAction={props.onManualAction} /><section className="panel-card"><div className="panel-head"><h2>任务与运行</h2><span className="muted">{props.state.tasks.length} 个任务</span></div><div className="stack">{props.state.tasks.map((task) => { const event = props.state.events.find((item) => item.id === task.eventSnapshotId); const runs = props.state.runs.filter((item) => item.taskId === task.id); return <article key={task.id} className="item-block"><div className="item-head"><div><strong>{event?.title ?? "未找到演出快照"}</strong><div className="item-meta"><StatusBadge status={task.status} /><span className="muted">{task.accountIds.length} 个账号</span></div></div><div className="row-actions">{task.status === "AwaitingConfirmation" ? <button className="icon-button" onClick={() => props.onEnqueue(task.id)}><Play size={15} />加入队列</button> : null}<button className="icon-button danger" onClick={() => props.onCancelTask(task.id)}><XCircle size={15} />取消任务</button></div></div><div className="runs">{runs.map((run) => <div key={run.id} className="run-row"><span>{props.state.accounts.find((account) => account.id === run.accountId)?.label || run.accountId}</span><StatusBadge status={run.status} /><button className="icon-button danger" onClick={() => props.onCancelRun(run.id)} title="取消该账号运行"><XCircle size={15} />取消运行</button></div>)}</div></article>; })}</div>{props.state.tasks.length === 0 ? <p className="empty-state">尚未创建任务。请在“创建任务”中开始配置。</p> : null}</section></section>; }
