import { ShieldAlert } from "lucide-react";
import type { Account, CreateTaskInputV2, EventSnapshot, LotteryPreference } from "../../shared/ipc.js";
import type { AvailableDayOption } from "../../shared/types.js";
type ConfirmationPolicy = CreateTaskInputV2["confirmationPolicy"];
const fallbackDayLabels: Record<"day1" | "day2", string> = { day1: "Day 1", day2: "Day 2" };
function dayLabel(day: "day1" | "day2", availableDays: readonly AvailableDayOption[]): string {
  return availableDays.find((option) => option.day === day)?.label ?? fallbackDayLabels[day];
}
export interface TaskDraft { readonly accountIds: string[]; readonly confirmationPolicy: ConfirmationPolicy; readonly preference: LotteryPreference; readonly riskAcknowledged: boolean; }
interface TaskPolicyControlsProps { readonly automated: boolean; readonly policy: ConfirmationPolicy; readonly acknowledged: boolean; readonly onPolicyChange: (policy: ConfirmationPolicy) => void; readonly onAcknowledgedChange: (value: boolean) => void; }
export function TaskPolicyControls(props: TaskPolicyControlsProps) { if (!props.automated) return null; return <div className="disclosure-stack" aria-label="自动化风险说明"><div className="disclosure disclosure-warning"><ShieldAlert size={18} aria-hidden="true" /><div><strong>自动化风险确认</strong><span>Eplus 条款可能限制自动化申请。请在创建任务前检查每个账号。</span></div></div><label className="full">最终确认策略<select value={props.policy} onChange={(event) => props.onPolicyChange(event.target.value === "disabled" ? "disabled" : "required")}><option value="required">需要确认：最终提交前暂停</option><option value="disabled">自动提交：不暂停</option></select></label><p className="muted">{props.policy === "disabled" ? "自动提交：每个账号提交前不会额外暂停。" : "需要确认：每个账号会在最终提交前等待明确确认。"}</p><label className="check-row"><input type="checkbox" checked={props.acknowledged} onChange={(event) => props.onAcknowledgedChange(event.target.checked)} />我已了解以上条款和自动化风险。</label></div>; }
interface PerAccountReviewProps { readonly accounts: readonly Account[]; readonly event: EventSnapshot | undefined; readonly draft: TaskDraft; readonly onDraftChange: (draft: TaskDraft) => void; }
function accountName(account: Account): string { return account.label || account.eplusEmail; }
export function PerAccountReview(props: PerAccountReviewProps) { const accounts = props.accounts.filter((account) => props.draft.accountIds.includes(account.id)); const days = props.event?.rawFormSchema.serialCode.availableDays ?? []; const needsDays = Boolean(props.event?.rawFormSchema.serialCode.daySelectionRequired && days.length > 1); const codes = props.draft.preference.serialCodesByAccountId ?? {}; const allocations = props.draft.preference.serialCodeAllocations ?? {}; const selections = props.draft.preference.daySelectionByAccountId ?? {}; const toggleDay = (id: string, day: "day1" | "day2") => { const current = selections[id] ?? []; props.onDraftChange({ ...props.draft, preference: { ...props.draft.preference, daySelectionByAccountId: { ...selections, [id]: current.includes(day) ? current.filter((item) => item !== day) : [...current, day] } } }); }; return <div className="account-review-list">{accounts.map((account) => { const plans = allocations[account.id] ?? (codes[account.id] || props.draft.preference.serialCode ? [{ code: codes[account.id] ?? props.draft.preference.serialCode ?? "", daySelection: selections[account.id] }] : []); const runCount = plans.reduce((total, plan) => total + Math.max(plan.daySelection?.length ?? 1, 1), 0); return <article key={account.id} className="account-review"><div><strong>{accountName(account)}</strong><span>{account.eplusEmail}</span></div>{needsDays && plans.length === 0 ? <div className="review-days" aria-label={`${accountName(account)}的场次选择`}>{days.map((day) => <label key={day.day} className="check-row"><input type="checkbox" checked={(selections[account.id] ?? []).includes(day.day)} onChange={() => toggleDay(account.id, day.day)} />{day.label}</label>)}</div> : null}{props.event?.rawFormSchema.serialCode.required ? <div className="review-serial-plans"><strong>{plans.length} 个抽选码 / {runCount} 次浏览器运行</strong>{plans.map((plan) => <span key={plan.code}><code>{plan.code}</code><small>{plan.daySelection?.length === 2 ? "两天 → 2 次独立运行" : plan.daySelection?.[0] ? `${dayLabel(plan.daySelection[0], days)} → 1 次运行` : "未指定场次"}</small></span>)}{plans.length === 0 ? <small className="muted">请在上方分配抽选码。</small> : null}</div> : null}<span className={props.draft.confirmationPolicy === "disabled" ? "badge badge-yellow" : "badge badge-teal"}>{props.draft.confirmationPolicy === "disabled" ? "自动提交" : "需要最终确认"}</span></article>; })}{accounts.length === 0 ? <p className="empty-state">至少选择一个已启用账号，才能预览其实际偏好。</p> : null}</div>; }
interface PreviewDigestProps { readonly event: EventSnapshot | undefined; readonly draft: TaskDraft; readonly accounts: readonly Account[]; }
export function PreviewDigest(props: PreviewDigestProps) { const selected = props.accounts.filter((account) => props.draft.accountIds.includes(account.id)); const days = props.draft.preference.daySelectionByAccountId ?? {}; return <div className="preview-digest" aria-live="polite"><div><span>演出</span><strong>{props.event?.title ?? "未选择演出快照"}</strong></div><div><span>账号</span><strong>{selected.length}</strong></div><div><span>策略</span><strong>{props.draft.confirmationPolicy === "disabled" ? "自动提交" : "需要最终确认"}</strong></div><div><span>场次选择</span><strong>{Object.values(days).filter((selection) => selection.length > 0).length || "不需要"}</strong></div></div>; }
